# Generated by Django 4.1.2 on 2022-12-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='number_courses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
