# Generated by Django 4.1.2 on 2022-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('department', models.CharField(max_length=64)),
                ('credits', models.IntegerField()),
            ],
        ),
    ]
