# Generated by Django 4.1.2 on 2022-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='verbose',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
