# Generated by Django 4.1.3 on 2022-11-09 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Courses',
            new_name='User_Course',
        ),
    ]
